//! Codex `requirements.toml`, per OpenAI's managed-configuration reference
//! as of 2026-09-24: `allowed_sandbox_modes`, `[experimental_network]`
//! (`enabled`, `managed_allowed_domains_only`, `domains` map of
//! `"name" = "allow"|"deny"`, `*.name` = subdomains, `**.name` = apex and
//! subdomains, deny wins) and `[permissions.filesystem] deny_read`. Install
//! it yourself at `/etc/codex/requirements.toml`; the broker never writes
//! system paths.

use super::{Export, Normalized};
use netguard::HostPattern;
use std::collections::BTreeMap;

fn q(s: &str) -> String {
    let mut o = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            c if c.is_control() => o.push_str(&format!("\\u{:04x}", c as u32)),
            c => o.push(c),
        }
    }
    o.push('"');
    o
}

fn list(v: &[String]) -> String {
    format!("[{}]", v.iter().map(|s| q(s)).collect::<Vec<_>>().join(", "))
}

pub fn export(n: &Normalized, profile: &str) -> Export {
    let mut domains: BTreeMap<String, &str> = BTreeMap::new();
    for h in &n.hosts {
        let name = match &h.pattern {
            HostPattern::Exact(x) => x.as_str().to_string(), // IPv6 already bracketed
            HostPattern::Subdomains(b) => format!("*.{}", b.as_str()),
        };
        domains.insert(name, "allow");
    }
    for c in &n.ceiling {
        domains.insert(format!("**.{c}"), "deny");
    }
    let mut s = String::new();
    s.push_str(&format!("# Generated by `broker policy export --target codex --profile {profile}`.\n"));
    s.push_str("# Defence in depth only: run the agent under `broker run`; the broker is the boundary.\n");
    s.push_str("# [experimental_network] is experimental in Codex; validate it on your client versions.\n\n");
    s.push_str("allowed_sandbox_modes = [\"read-only\", \"workspace-write\"]\n\n");
    s.push_str("[experimental_network]\nenabled = true\nmanaged_allowed_domains_only = true\n\n");
    s.push_str("[experimental_network.domains]\n");
    for (d, a) in &domains {
        s.push_str(&format!("{} = {}\n", q(d), q(a)));
    }
    s.push_str(&format!("\n[permissions.filesystem]\ndeny_read = {}\n", list(&n.deny_read)));
    let mut report = n.report.clone();
    report.push("ports are not expressible in [experimental_network.domains]; the broker enforces them".into());
    report.push("deny-write paths are not expressible in requirements.toml; the broker enforces them".into());
    report.push("MCP allowlist not exported: no pinned MCP servers yet (M3)".into());
    Export { file: s, report }
}

/// Does the exported file admit `host` under the documented matcher?
pub fn allows(file: &str, host: &str) -> bool {
    let v: toml::Value = toml::from_str(file).expect("exported TOML");
    let Some(d) = v.get("experimental_network").and_then(|n| n.get("domains")).and_then(|d| d.as_table()) else {
        return false;
    };
    let matches = |pat: &str| {
        if let Some(b) = pat.strip_prefix("**.") {
            host == b || host.ends_with(&format!(".{b}"))
        } else if let Some(b) = pat.strip_prefix("*.") {
            host.ends_with(&format!(".{b}"))
        } else {
            pat == host
        }
    };
    let hit = |want: &str| d.iter().any(|(k, a)| a.as_str() == Some(want) && matches(k));
    hit("allow") && !hit("deny")
}
